### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by muschellij2** [StevenMMortimer/squareupr#3]
What should the correct redirect URI be?

This must be specified.  Should it be `localhost` or `127.0.0.1`?

<img width="751" alt="Screen Shot 2020-04-08 at 4 56 06 PM" src="https://user-images.githubusercontent.com/1075118/78832795-dce30e80-79b9-11ea-93c3-77f5a1d92d47.png">

**Comment by StevenMMortimer** [comment]
@muschellij2 It depends on how you've configured the OAuth app, but typically it is this: 

```
http://localhost:1410/
```
